### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by dkoons1**
Hey guys, for some reason I dont think the API quotes was working on master and was lacking this last bit of code Elizabeth and Robbie worked on last night. Gonna create this request and see if this will fix the master page quote API.

### CODE REVIEW

**Review by Blayda — APPROVED** [review]

**Comment by dragon-stark** [comment]
Joji, I only pushed up to my homepage branch last night, (I think)
I also just updated the font and left some options comented in the .css file for you guys in case you don't love it

**Review by dragon-stark — APPROVED** [review]

**Comment by dragon-stark** [comment]
Hey guys, 
Did something happen, the chart looks like it’s not in a div again but it does have the font changes I added. I don’t think I deleted anything. 

Does it look ok on your end? 


Elizabeth

**Comment by dkoons1** [comment]
Yeah, it's happening on my end too, not sure why. All good though, I can
fix it later tonight unless someone wants to do it before hand haha.

**Comment by dkoons1** [comment]
Also, Elizabeth, the quote api thing looks awesome. Good job!

**Comment by dragon-stark** [comment]
Weird! I can try to edit later, I wasn’t sure if any of you were still doing anything to it. 
Also we can always restore it to the previous version but besides the double tables I’m really happy with it! 💪🏻

Elizabeth

**Comment by dkoons1** [comment]
Yeah, I'll definitely take a look at it later tonight and see if I can fix
it 👍

**Comment by dragon-stark** [comment]
Thank you! We ALL did a good job especially for our first try. Yeah!! 🌟 

Elizabeth

**Pull request merged**
